### ISSUE TITLE
How to identify entity ID?

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-monitoring#1]
If there is an INVALID_RESPONSE error because for example a required element in the XML is missing, how will the counterparty find out the ID of the entity (IIA ID, LA ID etc.)? Should this be added to the "message"? A more generic solution would be a new input parameter where all GET/POST parameters would be provided, including for example iia_id.

**Comment by m-sokolowski** [comment]
They should be able to find your request in their logs by looking at the timestamp of the report, so I think including identifiers in error reports is not necessary. If they can't find the error, they can always contact you directly and ask for more details.

> A more generic solution would be a new input parameter where all GET/POST parameters would be provided, including for example iia_id.

The request can contain personal data, as for example in https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/v1.2.0/endpoints/update.md, so we can't ask for all parameters.

**Comment by jiripetrzelka** [comment]
OK, that makes sense.
