### ISSUE TITLE
HTTP 200 + error-response

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-monitoring#3]
Which error_type and what message should be reported if the server returns HTTP 200 in combination with the error-response element?

**Comment by MBala98** [comment]
Hi Jiri, I believe the most suitable error_type here would be "INVALID_RESPONSE", as the server returned HTTP code 200, but had something unexpected/incorrect in the response body.

The message should be something that is easily understandable and conveys the meaning of the error, e.g "Incorrect response: unexpected element 'error-response'".

**Comment by m-sokolowski** [comment]
Here you can also find an example report from the EWP Stats Portal for such case: https://stats.erasmuswithoutpaper.eu/monitoring?group_by=&date_from=2023-05-01&date_to=2023-05-01&server_hei_id=unicas.it. The message is:

`Invalid response. Expected tag '{https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/stats-response.xsd}iias-stats-response', but got '{https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd}error-response'.`

**Comment by jiripetrzelka** [comment]
Thank you for clarification, we will report the unexpected tag.
